name: Summarize
description: Convenience wrapper to render different snippets of data to GITHUB_STEP_SUMMARY

inputs:
  header:
    description: Header to display before content
    required: false
    default: ""
  separator:
    description: Separator to add after content
    required: false
    default: ---

  json:
    description: JSON string, to be rendered in a `json` syntax block
    required: false
    default: ''

  command:
    description: Run command and display output in a `log` syntax block
    default: ""
    required: false
    
  collapse:
    description: If given, will wrap in a <details></details> tag with the argument as <summary>
    required: false
    default: ""

  save-as:
    description: If given, the markdown source after processing will be saved as an artifact with that name
    required: false
    default: ""

runs:
  using: composite
  steps:

    - shell: bash {0}
      run: |
        cat << 'EOF' >> $GITHUB_STEP_SUMMARY
        ${{ inputs.header }}

        EOF

    - shell: bash {0}
      if: inputs.json
      run: |
        cat << EOF >> $GITHUB_STEP_SUMMARY

        ${{ inputs.collapse && format('<details><summary>{0}</summary>', inputs.collapse) || ''}}

        \`\`\`json
        $(jq <<< '${{ inputs.json }}')
        \`\`\`

        ${{ inputs.collapse && '</details>' || ''}}
        EOF

    - shell: bash {0}
      if: inputs.command
      run: |
        cat << EOF >> $GITHUB_STEP_SUMMARY

        Output of \`${{ inputs.command }}\`:

        \`\`\`log
        $(${{ inputs.command }})
        \`\`\`

        EOF

    - if: inputs.save-as
      shell: bash {0}
      run: |
        cat $GITHUB_STEP_SUMMARY

