name: Post-pytest

on:
  workflow_run:
    types: [completed]
    workflows: [Try pytest]

jobs:

  coverage:
    runs-on: ubuntu-latest
    if: github.event.workflow_run.conclusion == 'success'
    steps:

      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Access artifacts using gh
        env:
          GH_TOKEN: ${{ github.token }}
        run:

          gh run download --repo ${{ github.repository }} --pattern="*coverage*"

          ls -lRth .
