name: Test actions

on:
  push:

jobs:
  install:
    name: Test 'install' action (${{ matrix.case }})
    runs-on: ${{ matrix.os-version }}
    strategy:
      fail-fast: false
      matrix:
        case:
          - case-1
          - case-2
        include:
          - case: case-1
            os-version: ubuntu-20.04
            python-environment: system
            python-version: '3.7'
            variant: editable
          - case: case-2
            os-version: windows-2019
            python-environment: conda
            python-version: '3.9'
            variant: noneditable
    steps:
      - uses: actions/checkout@v3
        if: matrix.variant == 'editable'
        with:
          repository: watertap-org/watertap
          ref: main
      - name: List dir contents
        run: |
          echo $PWD
          ls -Rlath $PWD
      - name: Run action
        uses: lbianchi-lbl/test-watertap-actions/install@main
        with:
          python-environment: ${{ matrix.python-environment }}
          python-version: ${{ matrix.python-version }}
          variant: ${{ matrix.variant }}
