name: Test custom-check action

on:
  push:
    paths:
      - custom-check/*
      - .github/workflows/test-custom-check.yml

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Test pending
        uses: ./custom-check
        with:
          token: ${{ secrets.WATERTAP_BOT_TOKEN }}
          repository: ${{ github.repository }}
          sha: ${{ github.sha }}
          title: My custom test [${{ github.event_name }}]
          body: Testing from ${{ github.workflow }} at $TIMESTAMP
          state: pending
          job-name: ${{ github.job }}
      - name: Wait after pending
        run: sleep 10
      - name: Test error
        uses: ./custom-check
        with:
          token: ${{ secrets.WATERTAP_BOT_TOKEN }}
          repository: ${{ github.repository }}
          sha: ${{ github.sha }}
          title: My custom test [${{ github.event_name }}]
          body: Testing from ${{ github.workflow }} at $TIMESTAMP
          state: error
          job-name: ${{ github.job }}
      - name: Wait after error
        run: sleep 10
      - name: Test failure
        uses: ./custom-check
        with:
          token: ${{ secrets.WATERTAP_BOT_TOKEN }}
          repository: ${{ github.repository }}
          sha: ${{ github.sha }}
          title: My custom test [${{ github.event_name }}]
          body: Testing from ${{ github.workflow }} at $TIMESTAMP
          state: failure
          job-name: ${{ github.job }}
      - name: Wait after failure
        run: sleep 10
      - name: Test success
        uses: ./custom-check
        with:
          token: ${{ secrets.WATERTAP_BOT_TOKEN }}
          repository: ${{ github.repository }}
          sha: ${{ github.sha }}
          title: My custom test [${{ github.event_name }}]
          body: Testing from ${{ github.workflow }} at $TIMESTAMP
          state: success
          job-name: ${{ github.job }}
