name: Test custom-check action

on:
  push:
    paths:
      - custom-check/*
      - .github/workflows/test-custom-check.yml

  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Test pending
        uses: ./custom-check
        with:
          repository: ${{ github.repository }}
          ref: ${{ github.sha }}
          title: Test [${{ github.event_name }}]
          body: Testing from ${{ github.workflow }} at $TIMESTAMP
          state: pending
          job-name: ${{ github.job }}
