name: Try pytest

concurrency:
  group: Try pytest
  cancel-in-progress: true

on:
  push:


jobs:

  get-commits-since:
    uses: ./.github/workflows/get-commits.yml
    with:
      repository: watertap-org/watertap
      ref: main
      since: 3 days ago

  display-commits:
    runs-on: ubuntu-latest
    needs: [get-commits-since]

    steps:

      - run: |
          cat << EOF >> $GITHUB_STEP_SUMMARY

          \`\`\`json
          $(jq <<< '${{ toJSON(needs.get-commits-since.outputs) }}')
          \`\`\`

          EOF

  call-pytest:
    needs: [get-commits-since]
    name: Run pytest (${{ fromJSON(needs.get-commits-since.outputs.sha-to-readable-map-json)[matrix.commit-sha] }})
    uses: ./.github/workflows/pytest.yml
    strategy:
      fail-fast: true
      matrix:
        commit-sha: ${{ fromJSON(needs.get-commits-since.outputs.shas-json )}}
    with:
      repository: watertap-org/watertap
      ref: ${{ matrix.commit-sha }}
      python-versions-json: '["3.8", "3.10"]'
      platforms-json: '["linux"]'
      variants-json: '["dev", "site"]'
      pytest-flags: --pyargs watertap.core
      pytest-extra-flags: -m unit
