name: Try pytest

concurrency: Try pytest

on:
  push:


jobs:
  
  call-pytest:
    uses: ./.github/workflows/pytest.yml
    with:
      repository: watertap-org/watertap
      ref: main
      python-versions-json: '["3.8", "3.10"]'
      platforms-json: '["linux", "win64"]'
      variants-json: '["dev", "site"]'
      pytest-flags: --pyargs watertap.core
      pytest-extra-flags: -m unit
