on:
  push:


jobs:
  
  call-pytest:
    uses: ./.github/workflows/pytest.yml
    with:
      python-versions-json: '["3.8", "3.10"]'
      platforms-json: '["linux", "win64"]'
      variants-json: '["dev", "site"]'

